# docker-compose.test.yml is used to spin up the app specifically for integration testing.

services:
  ui:
    build:
      target: production
    command: npm run start
    environment:
      NODE_ENV: production
      GUIDE_SEMANTIC_SEARCH_ENABLED: false
      NO_HTTPS: true
      INGRESS_URL: http://ui:3000

  playwright:
    image: mcr.microsoft.com/playwright:v1.60.0-noble
    networks:
      - hmpps
    depends_on:
      - ui
    environment:
      CI: true
      BASE_URL: http://ui:3000
      WIREMOCK_URL: http://wiremock:8080/__admin
    working_dir: /playwright
    command: npx playwright test
    volumes:
      - ../package.json:/playwright/package.json
      - ../package-lock.json:/playwright/package-lock.json
      - ../playwright.config.ts:/playwright/playwright.config.ts
      - ../integration_tests:/playwright/integration_tests
      - ../test_results:/playwright/test_results
      - node_modules:/playwright/node_modules

volumes:
  node_modules:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_examples_app_node_modules
