# `docker-compose.local.yml` defines services that must be run locally
# to support a fully self-contained local development environment.

services:
  ui:
    build:
      target: development
    working_dir: /app/examples-app
    command: npm run start:dev
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/health').then(r=>{process.exit(r.ok?0:1)}).catch(()=>process.exit(1))"]
    volumes:
      - ../../:/app
      - examples_app_node_modules:/app/examples-app/node_modules
      - examples_app_dist:/app/examples-app/dist
      - ../../packages/dist:/app/examples-app/node_modules/@ministryofjustice/hmpps-forge/dist
    environment:
      NODE_ENV: development
      ENVIRONMENT_NAME: dev
      NODE_CLUSTER_ENABLED: false

volumes:
  examples_app_node_modules:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_examples_app_node_modules
  examples_app_dist:
