// FORGE-EXAMPLE: Static data used by the add-trip step's `data` property.
// This demonstrates loading reference data into the step context without an API call.
// In a real service, this might come from a register or API endpoint instead.
// Using the country name as both value and text so the stored answer is human-readable.
export const countries = [
  { value: '', text: 'Select a country' },
  { value: 'Afghanistan', text: 'Afghanistan' },
  { value: 'Albania', text: 'Albania' },
  { value: 'Algeria', text: 'Algeria' },
  { value: 'Argentina', text: 'Argentina' },
  { value: 'Australia', text: 'Australia' },
  { value: 'Austria', text: 'Austria' },
  { value: 'Belgium', text: 'Belgium' },
  { value: 'Brazil', text: 'Brazil' },
  { value: 'Bulgaria', text: 'Bulgaria' },
  { value: 'Canada', text: 'Canada' },
  { value: 'China', text: 'China' },
  { value: 'Colombia', text: 'Colombia' },
  { value: 'Croatia', text: 'Croatia' },
  { value: 'Cyprus', text: 'Cyprus' },
  { value: 'Czech Republic', text: 'Czech Republic' },
  { value: 'Denmark', text: 'Denmark' },
  { value: 'Egypt', text: 'Egypt' },
  { value: 'Estonia', text: 'Estonia' },
  { value: 'Finland', text: 'Finland' },
  { value: 'France', text: 'France' },
  { value: 'Germany', text: 'Germany' },
  { value: 'Greece', text: 'Greece' },
  { value: 'Hungary', text: 'Hungary' },
  { value: 'India', text: 'India' },
  { value: 'Indonesia', text: 'Indonesia' },
  { value: 'Ireland', text: 'Ireland' },
  { value: 'Israel', text: 'Israel' },
  { value: 'Italy', text: 'Italy' },
  { value: 'Japan', text: 'Japan' },
  { value: 'Kenya', text: 'Kenya' },
  { value: 'Latvia', text: 'Latvia' },
  { value: 'Lithuania', text: 'Lithuania' },
  { value: 'Malaysia', text: 'Malaysia' },
  { value: 'Malta', text: 'Malta' },
  { value: 'Mexico', text: 'Mexico' },
  { value: 'Morocco', text: 'Morocco' },
  { value: 'Netherlands', text: 'Netherlands' },
  { value: 'New Zealand', text: 'New Zealand' },
  { value: 'Nigeria', text: 'Nigeria' },
  { value: 'Norway', text: 'Norway' },
  { value: 'Pakistan', text: 'Pakistan' },
  { value: 'Philippines', text: 'Philippines' },
  { value: 'Poland', text: 'Poland' },
  { value: 'Portugal', text: 'Portugal' },
  { value: 'Romania', text: 'Romania' },
  { value: 'Saudi Arabia', text: 'Saudi Arabia' },
  { value: 'Singapore', text: 'Singapore' },
  { value: 'Slovakia', text: 'Slovakia' },
  { value: 'Slovenia', text: 'Slovenia' },
  { value: 'South Africa', text: 'South Africa' },
  { value: 'South Korea', text: 'South Korea' },
  { value: 'Spain', text: 'Spain' },
  { value: 'Sweden', text: 'Sweden' },
  { value: 'Switzerland', text: 'Switzerland' },
  { value: 'Thailand', text: 'Thailand' },
  { value: 'Turkey', text: 'Turkey' },
  { value: 'United Arab Emirates', text: 'United Arab Emirates' },
  { value: 'United States', text: 'United States' },
  { value: 'Vietnam', text: 'Vietnam' },
]
