---
# Per environment values which override defaults in hmpps-template-typescript/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: forge-developer-guide-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://forge-developer-guide-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    NODE_USE_ENV_PROXY: "1"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
