name: Pipeline [test -> build -> deploy]

on:
  pull_request:
    paths:
      - '.github/workflows/pipeline.yml'
      - 'Makefile'
      - 'examples-app/**'
      - 'packages/**'
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable or testing tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}

jobs:
  static_checks:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Lint packages
            working_directory: packages
            command: npm run lint
            build_packages: false
          - name: Typecheck packages
            working_directory: packages
            command: npm run typecheck
            build_packages: false
          - name: Lint examples-app
            working_directory: examples-app
            command: npm run lint
            build_packages: true
          - name: Typecheck examples-app
            working_directory: examples-app
            command: npm run typecheck
            build_packages: true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install packages dependency
        if: matrix.build_packages
        working-directory: packages
        run: npm ci
      - name: Build packages dependency
        if: matrix.build_packages
        working-directory: packages
        run: npm run build
      - name: Install dependencies
        working-directory: ${{ matrix.working_directory }}
        run: npm ci
      - name: Run check
        working-directory: ${{ matrix.working_directory }}
        run: ${{ matrix.command }}
  packages_tests:
    name: Test packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install packages dependencies
        working-directory: packages
        run: npm ci
      - name: Build packages
        working-directory: packages
        run: npm run build
      - name: Test packages
        working-directory: packages
        run: npm run test
  examples_app_tests:
    name: Test examples-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install packages dependencies
        working-directory: packages
        run: npm ci
      - name: Build packages
        working-directory: packages
        run: npm run build
      - name: Install examples-app dependencies
        working-directory: examples-app
        run: npm ci
      - name: Test examples-app
        working-directory: examples-app
        run: npm run test:ci
      - name: Build examples-app
        working-directory: examples-app
        run: npm run build
      - name: Run end-to-end tests
        run: make e2e-ci
  validate:
    name: Validate
    if: always()
    runs-on: ubuntu-latest
    needs:
      - static_checks
      - packages_tests
      - examples_app_tests
    steps:
      - name: Check validation jobs
        run: |
          if [ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" = "true" ]; then
            exit 1
          fi
  helm_lint:
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        environments: ['dev']
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}
      chart_name: hmpps-forge-examples-app
  build:
    name: Build and push docker image
    if: github.event_name != 'pull_request'
    needs:
      - validate
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install and build packages
        working-directory: packages
        run: |
          npm ci
          npm run build
      - name: Create app version
        id: version
        uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/build-test-and-deploy/create_app_version@v1
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: examples-app/Dockerfile
          push: ${{ inputs.push || inputs.push == null }}
          tags: |
            ghcr.io/ministryofjustice/hmpps-forge-examples-app:${{ steps.version.outputs.version }}
            ghcr.io/ministryofjustice/hmpps-forge-examples-app:latest
          build-args: |
            BUILD_NUMBER=${{ steps.version.outputs.version }}
            GIT_REF=${{ github.sha }}
            GIT_BRANCH=${{ github.ref_name }}
  deploy_dev:
    name: Deploy to the development environment
    if: github.event_name != 'pull_request'
    needs:
      - build
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'dev'
      app_version: '${{ needs.build.outputs.app_version }}'
      helm_chart_name: 'hmpps-forge-examples-app'
      k8s_deployment_name: 'hmpps-forge-examples-app'
      helm_timeout: '10m'
      slack_notification: 'false'
