name: Pipeline [test -> build -> deploy]

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable or testing tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}

jobs:
  validate_packages:
    name: validate packages
    uses: ./.github/workflows/packages_pipeline.yml
  validate_examples_app:
    name: validate examples-app
    uses: ./.github/workflows/examples_app_pipeline.yml
  helm_lint:
    strategy:
      matrix:
        environments: ['dev']
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}
#  build:
#    name: Build docker image from hmpps-github-actions
#    if: github.ref == 'refs/heads/main'
#    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2 # WORKFLOW_VERSION
#    needs:
#      - validate_packages
#      - validate_examples_app
#    with:
#      docker_registry: 'ghcr.io'
#      registry_org: 'ministryofjustice'
#      additional_docker_tag: ${{ inputs.additional_docker_tag }}
#      push: ${{ inputs.push || inputs.push == null }}
#      docker_multiplatform: false
#  deploy_dev:
#    name: Deploy to the development environment
#    needs:
#      - build
#      - helm_lint
#    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
#    secrets: inherit
#    with:
#      environment: 'dev'
#      app_version: '${{ needs.build.outputs.app_version }}'
#      slack_notification: 'false' # if 'true', it needs a valid NONPROD_RELEASES_SLACK_CHANNEL variable to be set
